// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Qerp.Models
{
    public partial class City
    {
        public City()
        {

        }

        public long Id { get; set; }
        public long CompanyId { get; set; }
        public long? CountryId { get; set; }
        public long? ProvinceId { get; set; }
        public string PostalCode { get; set; }
        public string Name { get; set; }
        public string ImportProvince { get; set; }

        public virtual Company Company { get; set; }
        public virtual Country Country { get; set; }
        public virtual Province Province { get; set; }

    }
}