// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Bogus.DataSets;
using System;
using System.Collections.Generic;

namespace Qerp.Models
{
    public partial class Contact
    {
        public Contact()
        {
            Images = new HashSet<Image>();
        }

        public long Id { get; set; }
        public long ApptypeId { get; set; }
        public long CompanyId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Fullname { get; set; }
        public string Address { get; set; }
        public long? CityId { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public DateTime Created { get; set; }
        public DateTime Updated { get; set; }

        public virtual City? City { get; set; }
        public virtual Company? Company { get; set; }

        public virtual ICollection<Models.Image> Images { get; set; }

    }
}