// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Qerp.Models
{
    public partial class Image
    {
        public long Id { get; set; }
        public long LinkedapptypeId { get; set; }
        public long LinkedtypeId { get; set; }
        public string Description { get; set; }
        public string Extension { get; set; }
        public string Filename { get; set; }
        public string Imagelink { get; set; }
        public string Thumblink { get; set; }
        public int? Sort { get; set; }
        public DateTime Created { get; set; }
        public DateTime Updated { get; set; }

        public virtual Client Client { get; set; }
        public virtual Contact Contact { get; set; }

    }
}