// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Qerp.Models
{
    public partial class Invoice
    {
        public Invoice()
        {

        }

        public long Id { get; set; }
        public long ApptypeId { get; set; }
        public long CompanyId { get; set; }
        public long ClientId { get; set; }
        public long ProjectId { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public ulong? IsCreditNote { get; set; }
        public ulong? Sent { get; set; }
        public DateTime Created { get; set; }

        public virtual Client Client { get; set; }
        public virtual Company Company { get; set; }
        public virtual Project Project { get; set; }

    }
}