// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Qerp.DBContext;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Qerp.Models
{
    public partial class Milestone
    {
        public Milestone()
        {
        }

        public long Id { get; set; }
        public long CompanyId { get; set; }
        public long ApptypeId { get; set; }
        public long? LinkedapptypeId { get; set; }
        public long? LinkedtypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? Deadline { get; set; }
        public ulong? Completed { get; set; }
        public DateTime Created { get; set; }
        public DateTime Updated { get; set; }

        public virtual Company Company { get; set; }
        public virtual Project Project { get; set; }
        public virtual Prospect Prospect { get; set; }

        [NotMapped]
        public int TaskCount
        {
            get
            {
                using QerpContext db = new QerpContext();
                int count = db.Tasks.Where(t => t.MilestoneId == this.Id).Count();
                return count;
            }
        }

        [NotMapped]
        public int TasksCompleted
        {
            get
            {
                using QerpContext db = new QerpContext();
                int count = db.Tasks.Where(t => t.MilestoneId == this.Id && t.Completed == 1).Count();
                return count;
            }
        }

        [NotMapped]
        public int PercentageCompleted
        {
            get
            {
                return this.TaskCount > 0 ? (int)Math.Ceiling(((double)this.TasksCompleted / this.TaskCount * 100)) : 0; 
            }
        }
    }
}