// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Qerp.Models
{
    public partial class Milestone
    {
        public Milestone()
        {
        }

        public long Id { get; set; }
        public long CompanyId { get; set; }
        public long ApptypeId { get; set; }
        public long? LinkedapptypeId { get; set; }
        public long? LinkedtypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? Deadline { get; set; }
        public ulong? Completed { get; set; }
        public DateTime Created { get; set; }
        public DateTime Updated { get; set; }

        public virtual Company Company { get; set; }
        public virtual Project Project { get; set; }
        public virtual Prospect Prospect { get; set; }
    }
}