// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Qerp.Models
{
    public partial class Parametergroup
    {
        public Parametergroup()
        {
            Parameters = new HashSet<Parameter>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string Systemcode { get; set; }
        public int Sort { get; set; }
        public ulong? CanEdit { get; set; }

        public virtual ICollection<Parameter> Parameters { get; set; }
    }
}