// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Qerp.Models
{
    public partial class Prospectgoal
    {
        public Prospectgoal()
        {

        }

        public long Id { get; set; }
        public long ProspectId { get; set; }
        public string Description { get; set; }
        public DateTime? Deadline { get; set; }
        public DateTime Created { get; set; }
        public DateTime Updated { get; set; }

        public virtual Prospect Prospect { get; set; }

    }
}