// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Qerp.Models
{
    public partial class Saveditem
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public int? ApptypeId { get; set; }
        public string Name { get; set; }
        public string Routelink { get; set; }
        public DateTime Created { get; set; }

        public virtual User User { get; set; }
    }
}